import {
  BLOB_GET_MAX_BYTES as DEFAULT_BLOB_GET_MAX_BYTES,
  UPLOAD_CHUNKED_MAX_MD_BYTES as DEFAULT_UPLOAD_CHUNKED_MAX_MD_BYTES,
  UPLOAD_CHUNKED_MAX_PDF_BYTES as DEFAULT_UPLOAD_CHUNKED_MAX_PDF_BYTES,
  PDF_PARSE_MAX_BYTES as DEFAULT_PDF_PARSE_MAX_BYTES,
  PDF_PARSE_MAX_PAGES as DEFAULT_PDF_PARSE_MAX_PAGES,
  PDF_PARSE_MAX_CHARS as DEFAULT_PDF_PARSE_MAX_CHARS,
  CCH_MODEL as DEFAULT_CCH_MODEL,
  MD_CHUNK_DELIMITER as DEFAULT_MD_CHUNK_DELIMITER,
  INGEST_CHUNK_SIZE as DEFAULT_INGEST_CHUNK_SIZE,
  PARENT_CHUNK_SIZE as DEFAULT_PARENT_CHUNK_SIZE,
  CHILD_CHUNK_SIZE as DEFAULT_CHILD_CHUNK_SIZE,
  PARENT_CHILD_MODE as DEFAULT_PARENT_CHILD_MODE,
  PARENT_CHILD_WINDOW as DEFAULT_PARENT_CHILD_WINDOW,
  RERANKER_PROVIDER as DEFAULT_RERANKER_PROVIDER,
  CANDIDATE_POOL as DEFAULT_CANDIDATE_POOL,
  RERANK_TOP_N as DEFAULT_RERANK_TOP_N,
  RRF_K as DEFAULT_RRF_K,
  LEXICAL_WEIGHT as DEFAULT_LEXICAL_WEIGHT,
  GRADE_MODEL as DEFAULT_GRADE_MODEL,
  OUT_OF_DOMAIN_THRESHOLD as DEFAULT_OUT_OF_DOMAIN_THRESHOLD,
  AGENT_STEP_BUDGET as DEFAULT_AGENT_STEP_BUDGET,
  AGENTIC_RETRIEVE_LIMIT as DEFAULT_AGENTIC_RETRIEVE_LIMIT,
  AGENTIC_MAX_RETRIES as DEFAULT_AGENTIC_MAX_RETRIES,
  ANSWER_CACHE_TTL_SEC as DEFAULT_ANSWER_CACHE_TTL_SEC,
  EVAL_FAITHFULNESS_THRESHOLD as DEFAULT_EVAL_FAITHFULNESS_THRESHOLD,
} from '@app/domain';
import type { LogLevel } from '@app/domain';

const VALID_LOG_LEVELS: readonly LogLevel[] = ['error', 'warn', 'info', 'debug'];

function finiteOrDefault(value: string | undefined, fallback: number): number {
  const n = value === undefined ? NaN : Number(value);
  return Number.isFinite(n) ? n : fallback;
}

export const LOG_LEVEL: LogLevel = VALID_LOG_LEVELS.includes(process.env.LOG_LEVEL as LogLevel)
  ? (process.env.LOG_LEVEL as LogLevel)
  : 'info';

export const BLOB_GET_MAX_BYTES = finiteOrDefault(process.env.BLOB_GET_MAX_BYTES, DEFAULT_BLOB_GET_MAX_BYTES);
export const UPLOAD_CHUNKED_MAX_MD_BYTES = finiteOrDefault(process.env.UPLOAD_CHUNKED_MAX_MD_BYTES, DEFAULT_UPLOAD_CHUNKED_MAX_MD_BYTES);
export const UPLOAD_CHUNKED_MAX_PDF_BYTES = finiteOrDefault(process.env.UPLOAD_CHUNKED_MAX_PDF_BYTES, DEFAULT_UPLOAD_CHUNKED_MAX_PDF_BYTES);
export const PDF_PARSE_MAX_BYTES = finiteOrDefault(process.env.PDF_PARSE_MAX_BYTES, DEFAULT_PDF_PARSE_MAX_BYTES);
export const PDF_PARSE_MAX_PAGES = finiteOrDefault(process.env.PDF_PARSE_MAX_PAGES, DEFAULT_PDF_PARSE_MAX_PAGES);
export const PDF_PARSE_MAX_CHARS = finiteOrDefault(process.env.PDF_PARSE_MAX_CHARS, DEFAULT_PDF_PARSE_MAX_CHARS);
export const CCH_ENABLED = process.env.CCH_ENABLED !== 'false';
export const CCH_MODEL = process.env.CCH_MODEL ?? DEFAULT_CCH_MODEL;
export const MD_CHUNK_DELIMITER = process.env.MD_CHUNK_DELIMITER ?? DEFAULT_MD_CHUNK_DELIMITER;
export const INGEST_CHUNK_SIZE = finiteOrDefault(process.env.INGEST_CHUNK_SIZE, DEFAULT_INGEST_CHUNK_SIZE);
export const INGEST_CHUNK_OVERLAP = Math.floor(INGEST_CHUNK_SIZE / 10);
export const PARENT_CHUNK_SIZE = finiteOrDefault(process.env.PARENT_CHUNK_SIZE, DEFAULT_PARENT_CHUNK_SIZE);
export const CHILD_CHUNK_SIZE = finiteOrDefault(process.env.CHILD_CHUNK_SIZE, DEFAULT_CHILD_CHUNK_SIZE);
export const PARENT_CHILD_MODE = (process.env.PARENT_CHILD_MODE ?? DEFAULT_PARENT_CHILD_MODE) as 'parent' | 'window';
export const PARENT_CHILD_WINDOW = finiteOrDefault(process.env.PARENT_CHILD_WINDOW, DEFAULT_PARENT_CHILD_WINDOW);
export const RERANKER_PROVIDER = (process.env.RERANKER_PROVIDER ?? DEFAULT_RERANKER_PROVIDER) as 'cosine' | 'local' | 'cohere';
export const CANDIDATE_POOL = finiteOrDefault(process.env.CANDIDATE_POOL, DEFAULT_CANDIDATE_POOL);
export const RERANK_TOP_N = finiteOrDefault(process.env.RERANK_TOP_N, DEFAULT_RERANK_TOP_N);
export const HYBRID_ENABLED = process.env.HYBRID_ENABLED !== 'false';
export const RRF_K = finiteOrDefault(process.env.RRF_K, DEFAULT_RRF_K);
export const LEXICAL_WEIGHT = finiteOrDefault(process.env.LEXICAL_WEIGHT, DEFAULT_LEXICAL_WEIGHT);
export const AGENTIC_ENABLED = process.env.AGENTIC_ENABLED !== 'false';
export const GRADE_MODEL = process.env.GRADE_MODEL ?? DEFAULT_GRADE_MODEL;
export const OUT_OF_DOMAIN_THRESHOLD = finiteOrDefault(process.env.OUT_OF_DOMAIN_THRESHOLD, DEFAULT_OUT_OF_DOMAIN_THRESHOLD);
export const AGENT_STEP_BUDGET = finiteOrDefault(process.env.AGENT_STEP_BUDGET, DEFAULT_AGENT_STEP_BUDGET);
export const AGENTIC_RETRIEVE_LIMIT = finiteOrDefault(process.env.AGENTIC_RETRIEVE_LIMIT, DEFAULT_AGENTIC_RETRIEVE_LIMIT);
export const AGENTIC_MAX_RETRIES = finiteOrDefault(process.env.AGENTIC_MAX_RETRIES, DEFAULT_AGENTIC_MAX_RETRIES);
export const ANSWER_CACHE_ENABLED = process.env.ANSWER_CACHE_ENABLED !== 'false';
export const ANSWER_CACHE_TTL_SEC = finiteOrDefault(process.env.ANSWER_CACHE_TTL_SEC, DEFAULT_ANSWER_CACHE_TTL_SEC);
export const TRACE_ENABLED = process.env.TRACE_ENABLED === 'true';
export const EVAL_FAITHFULNESS_THRESHOLD = finiteOrDefault(process.env.EVAL_FAITHFULNESS_THRESHOLD, DEFAULT_EVAL_FAITHFULNESS_THRESHOLD);
